name: CI/CD for API REST2

on:
  push:
    branches:
      - master

jobs:
  testing:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

        
  build_and_push_image:
    name: Build and push Docker image
    runs-on: ubuntu-latest
    needs: testing
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Clear Docker credentials
        run: docker logout || true

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ralvarado0505/api-rest:latest


  deploy_to_ec2:
    name: Deploy to AWS EC2
    runs-on: ubuntu-latest
    needs: build_and_push_image
    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.AWS_EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.AWS_PRIVATE_KEY }}
          script: |
            docker pull ralvarado0505/api-rest:latest
            docker stop api || true
            docker rm api || true
            docker run -d --name api -p 8080:8080 ralvarado0505/api-rest:latest
